security:
    encoders:
        App\Entity\User: 
            algorithm: bcrypt
    providers:
        # in_memory: { memory: ~ }
        my_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/, roles: [ROLE_USER] }
        # - { path: ^/manage, roles: [ROLE_USER] }
        # - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }